import {
  Home,
  Dumbbell,
  Swords,
  Trophy,
  BarChart3,
  User,
  Flame,
  Star,
  Check,
  X,
  Lock,
  Target,
  Zap,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleX,
  TriangleAlert,
  Info,
  Loader2,
  ArrowLeft,
  BookOpen,
  RotateCcw,
  Sparkles,
  FileText,
  PenLine,
  Lightbulb,
  Globe,
  Users,
  Code2,
  Atom,
  Crown,
  Menu,
  Search,
  Calculator,
  StickyNote,
  FunctionSquare,
  LayoutTemplate,
  BookMarked,
  Flag,
  Paintbrush,
  Eraser,
  Undo2,
  Redo2,
  Trash2,
  Ruler,
  Eye,
  Bookmark,
  Heart,
  Filter,
  Calendar,
  Settings,
  HelpCircle,
  LogOut,
  Moon,
  ChevronLeft,
  ArrowRight,
  TrendingUp,
  Clock,
  Percent,
  Medal,
  Gift,
  Rocket,
  Gem,
  GraduationCap,
  PlayCircle,
  MoreVertical,
  LayoutGrid,
  UserPlus,
  Keyboard,
  RefreshCw,
  ClipboardCheck,
  MessageCircleQuestion,
  Palette,
  SquareRadical,
  LineChart,
  Triangle,
  Box,
  Dices,
  TrendingDown,
  Inbox,
  ListChecks,
  Square,
  CheckSquare,
  Plus,
  Brain,
  MessageCircle,
  Users2,
  FlaskConical,
  Leaf,
  Landmark,
  Bell,
  Shield,
  Copy,
  Share2,
  Pencil,
  Pause,
  type LucideIcon,
} from 'lucide-react';

/**
 * One coherent icon set for the whole product (Design Spec Section 3):
 * outline strokes from lucide-react, with a shared "filled" look
 * available via <Icon filled /> for active/selected states. New icons
 * get added here, never imported ad hoc in a screen — keeps the icon
 * language consistent.
 */
export const icons = {
  home: Home,
  training: Dumbbell,
  battles: Swords,
  achievements: Trophy,
  progress: BarChart3,
  profile: User,
  flame: Flame,
  star: Star,
  check: Check,
  error: X,
  lock: Lock,
  target: Target,
  xp: Zap,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  close: X,
  success: CircleCheck,
  errorCircle: CircleX,
  warning: TriangleAlert,
  info: Info,
  spinner: Loader2,
  back: ArrowLeft,
  topic: BookOpen,
  mistakes: RotateCcw,
  smart: Sparkles,
  variant: FileText,
  scratchboard: PenLine,
  hint: Lightbulb,
  subjectEnglish: Globe,
  subjectSocial: Users,
  subjectInformatics: Code2,
  subjectPhysics: Atom,
  crown: Crown,
  menu: Menu,
  search: Search,
  calculator: Calculator,
  notes: StickyNote,
  fxInput: FunctionSquare,
  templates: LayoutTemplate,
  reference: BookMarked,
  skip: Flag,
  showSolution: Eye,
  bookmark: Bookmark,
  brush: Paintbrush,
  eraser: Eraser,
  undo: Undo2,
  redo: Redo2,
  clear: Trash2,
  ruler: Ruler,
  favorite: Heart,
  filter: Filter,
  calendar: Calendar,
  settings: Settings,
  faq: HelpCircle,
  logout: LogOut,
  theme: Moon,
  chevronLeft: ChevronLeft,
  arrowRight: ArrowRight,
  trend: TrendingUp,
  time: Clock,
  percent: Percent,
  medal: Medal,
  gift: Gift,
  rocket: Rocket,
  gem: Gem,
  graduation: GraduationCap,
  play: PlayCircle,
  more: MoreVertical,
  grid: LayoutGrid,
  friends: UserPlus,
  keyboard: Keyboard,
  retry: RefreshCw,
  analysis: ClipboardCheck,
  question: MessageCircleQuestion,
  palette: Palette,
  topicEquations: SquareRadical,
  topicFunctions: LineChart,
  topicPlanimetry: Triangle,
  topicStereometry: Box,
  topicProbability: Dices,
  trendDown: TrendingDown,
  emptyState: Inbox,
  checklist: ListChecks,
  checkboxEmpty: Square,
  checkboxChecked: CheckSquare,
  add: Plus,
  brain: Brain,
  chat: MessageCircle,
  community: Users2,
  subjectChemistry: FlaskConical,
  subjectBiology: Leaf,
  subjectHistory: Landmark,
  notifications: Bell,
  bank: Landmark,
  shield: Shield,
  language: Globe,
  copy: Copy,
  share: Share2,
  edit: Pencil,
  pause: Pause,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
